stages:
  - test

Cypress Tests:
  stage: test
  image: cypress/included:8.3.0
  script:
    - npm ci
    - npx cypress run --browser chrome --env environmentName=homolog
    - cp cypress/reports/html/index.html $CI_PROJECT_DIR/index.html
  artifacts:
    paths:
      - index.html